services:
  - type: web
    name: emr-analysis
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      PYTHON_VERSION: 3.11.8
